# LAMMPS init file

#===========================================================
# Initialize System
#===========================================================

# File-wide variables
variable    prefix              index    test
variable    coords_freq         index    100
variable    vseed               index    83718

# System definition
units lj
dimension 3
newton on
boundary p p p
atom_style full
run_style verlet
neigh_modify every 1 delay 10 check yes one 10000

# Force-field definition
special_bonds   lj 0.0 0.0 0.0 coul 0.0 0.0 0.0
pair_style      lj/cut 3.0
pair_modify     shift yes mix sixthpower
bond_style      harmonic
angle_style     harmonic
dihedral_style  opls
improper_style  cvff

# Data, settings, and log files setup
read_data test.in.data
include test.in.settings
log ${prefix}.lammps.log
thermo_style custom temp press ke pe
thermo_modify format float %14.6f
thermo 100

# Thermodynamic averages file setup
# "Nevery Nrepeat Nfreq": On every "Nfreq" steps, take the averages by using "Nrepeat" previous steps, counted every "Nevery"
variable calc_temp equal temp
variable calc_press equal press
variable calc_ke equal ke
variable calc_pe equal pe
fix averages all ave/time 5 10 50 v_calc_temp v_calc_press v_calc_ke v_calc_pe file ${prefix}.thermo.avg format %20.10g

#===========================================================
# shrink (nvt deform)
#===========================================================

timestep 0.001
velocity all create 1.267 83718
dump shrink all custom ${coords_freq} ${prefix}.shrink.lammpstrj id mol type xu yu zu vx vy vz
dump_modify shrink sort id format float %20.10g
fix shrink_deform all deform 1 x final -4.0 4.0 y final -4.0 4.0 z final -4.0 4.0 units box
fix shrink_nvt all nvt temp 1.267 1.267 0.425
run 15000
unfix shrink_deform
unfix shrink_nvt
undump shrink
write_restart shrink.restart

#===========================================================
# diffusion (nvt)
#===========================================================

timestep 0.001
velocity all create 1.267 83718
dump diffusion all custom ${coords_freq} ${prefix}.diffusion.lammpstrj id mol type xu yu zu vx vy vz
dump_modify diffusion sort id format float %20.10g
fix diffusion all nvt temp 1.267 1.267 0.425
run 50000
unfix diffusion
undump diffusion
write_restart diffusion.restart

#===========================================================
# Clean and exit
#===========================================================

unfix averages
write_data ${prefix}.end.data
write_restart ${prefix}.end.restart