# LAMMPS init file

#===========================================================
# Variables
#===========================================================

# File-wide variables
variable    settings_name    index    test.in.settings
variable    prefix           index    test-1
variable    thermo_freq      index    1000
variable    avg_freq         index    1000
variable    dump4avg         index    100
variable    coords_freq      index    1000
variable    vseed            index    123

# relax
variable    nSteps_relax    index    1000 # fs
variable    press0_relax    index    1.0 # atm
variable    pressf_relax    index    1.0 # atm
variable    temp0_relax     index    10.0 # K
variable    tempf_relax     index    10.0 # K

# density
variable    nSteps_density    index    100000 # fs
variable    press0_density    index    1.0 # atm
variable    pressf_density    index    1.0 # atm
variable    temp0_density     index    100.0 # K
variable    tempf_density     index    100.0 # K

# heat
variable    nSteps_heat    index    10000000 # fs
variable    press0_heat    index    1.0 # atm
variable    pressf_heat    index    1.0 # atm
variable    temp0_heat     index    100.0 # K
variable    tempf_heat     index    300.0 # K

# equil
variable    nSteps_equil    index    10000000 # fs
variable    press0_equil    index    1.0 # atm
variable    pressf_equil    index    1.0 # atm
variable    temp0_equil     index    300.0 # K
variable    tempf_equil     index    300.0 # K

#===========================================================
# Initialize System
#===========================================================

units real
dimension 3
newton on
boundary p p p
atom_style molecular
log ${prefix}.lammps.log

#===========================================================
# Force Field Definitions
#===========================================================

special_bonds   lj 0.0 0.0 0.0 coul 0.0 0.0 0.0    # NO 1-4 LJ/COUL interactions
pair_style      lj/cut 9.0
pair_modify     shift yes mix sixthpower           # using Waldman-Hagler mixing rules
bond_style      harmonic
angle_style     harmonic
dihedral_style  opls
improper_style  cvff

#===========================================================
# Setup System
#===========================================================

read_data test-1.in.data
include ${settings_name}
run_style verlet # Velocity-Verlet integrator
neigh_modify every 1 delay 10 check yes one 10000

thermo_style custom temp press ke pe
thermo_modify format float %20.10f
thermo ${thermo_freq}

variable    my_temp  equal  temp
variable    my_press  equal  press
variable    my_ke  equal  ke
variable    my_pe  equal  pe

# Set the averages fix
fix averages all ave/time ${dump4avg} $(v_avg_freq/v_dump4avg) ${avg_freq} v_my_temp v_my_press v_my_ke v_my_pe file ${prefix}.thermo.avg

# Set momentum fix to zero out momentum (linear and angular) every ps
fix mom all momentum 1000 linear 1 1 1 angular
velocity all create ${temp0_relax} ${vseed} mom yes rot yes

#===========================================================
# relax (nve/limit)
#===========================================================

timestep 0.25
dump relax all custom ${coords_freq} ${prefix}.relax.lammpstrj id mol type xu yu zu vx vy vz
dump_modify relax sort id format float %20.10g
fix nve_relax all nve/limit 0.1 
run ${nSteps_relax}
unfix nve_relax
undump relax

#===========================================================
# density (npt, Nose-Hoover)
#===========================================================

timestep 1.0
dump density all custom ${coords_freq} ${prefix}.density.lammpstrj id mol type xu yu zu vx vy vz
dump_modify density sort id format float %20.10g
fix density all npt temp ${temp0_density} ${tempf_density} 100.0 iso ${press0_density} ${pressf_density} 100.0
run ${nSteps_density}
unfix density
undump density

#===========================================================
# heat (npt, Nose-Hoover)
#===========================================================

timestep 1.0
dump heat all custom ${coords_freq} ${prefix}.heat.lammpstrj id mol type xu yu zu vx vy vz
dump_modify heat sort id format float %20.10g
fix heat all npt temp ${temp0_heat} ${tempf_heat} 100.0 iso ${press0_heat} ${pressf_heat} 100.0
run ${nSteps_heat}
unfix heat
undump heat

#===========================================================
# equil (npt, Nose-Hoover)
#===========================================================

timestep 1.0
dump equil all custom ${coords_freq} ${prefix}.equil.lammpstrj id mol type xu yu zu vx vy vz
dump_modify equil sort id format float %20.10g
fix equil all npt temp ${temp0_equil} ${tempf_equil} 100.0 iso ${press0_equil} ${pressf_equil} 100.0
run ${nSteps_equil}
unfix equil
undump equil

#===========================================================
# Clean and exit
#===========================================================

write_data ${prefix}.end.data
unfix averages
unfix mom
