# LAMMPS init file

#===========================================================
# Variables
#===========================================================

# File-wide variables
variable    settings_name    index    test_diffusionscaling.in.settings
variable    prefix           index    test_diffusionscaling
variable    thermo_freq      index    1000
variable    avg_freq         index    1000
variable    dump4avg         index    100
variable    coords_freq      index    1000
variable    vseed            index    123

#===========================================================
# Initialize System
#===========================================================

units real
dimension 3
newton on
boundary p p p
atom_style molecular
log ${prefix}.lammps.log

#===========================================================
# Force Field Definitions
#===========================================================

special_bonds   lj 0.0 0.0 0.0 coul 0.0 0.0 0.0    # No 1-4 LJ/Coul interactions
pair_style      lj/cut 9.0
pair_modify     shift yes mix sixthpower           # using Waldman-Hagler mixing rules
bond_style      harmonic
angle_style     harmonic
dihedral_style  opls
improper_style  cvff

#===========================================================
# Setup System
#===========================================================

read_data ${prefix}.in.data
include ${settings_name}
run_style verlet
neigh_modify every 1 delay 10 check yes one 10000

thermo_style custom temp press ke pe
thermo_modify format float %20.10f
thermo ${thermo_freq}

variable    my_temp  equal  temp
variable    my_press  equal  press
variable    my_ke  equal  ke
variable    my_pe  equal  pe

# Set the averages fix
fix averages all ave/time ${dump4avg} $(v_avg_freq/v_dump4avg) ${avg_freq} v_my_temp v_my_press v_my_ke v_my_pe file ${prefix}.thermo.avg

# Set momentum fix to zero out momentum (linear and angular) every ps
fix mom all momentum 1000 linear 1 1 1 angular
velocity all create 10 ${vseed} mom yes rot yes

#===========================================================
# energy minimization (nve/limit)
#===========================================================

timestep 0.25
dump emin all custom 100 ${prefix}.emin.lammpstrj id mol type xu yu zu vx vy vz
dump_modify emin sort id format float %20.10g
fix nve_emin all nve/limit 0.1 
run 10000
unfix nve_emin
undump emin

#===========================================================
# density adjustment (npt, Nose-Hoover)
#===========================================================

timestep 1.0
dump density all custom 100 ${prefix}.density.lammpstrj id mol type xu yu zu vx vy vz
dump_modify density sort id format float %20.10g
fix npt_density all npt temp 10.0 10.0 100.0 iso 1.0 1.0 100.0
run 1000000
unfix npt_density
undump density

#===========================================================
# equilibration (npt, Nose-Hoover)
#===========================================================

timestep 1.0
dump equil all custom 100 ${prefix}.equil.lammpstrj id mol type xu yu zu vx vy vz
dump_modify equil sort id format float %20.10g
fix npt_equil all npt temp 10.0 300.0 100.0 iso 1.0 1.0 100.0
run 1000000
unfix npt_equil
undump equil

#===========================================================
# production (npt, Nose-Hoover)
#===========================================================

timestep 1.0
dump production all custom 1000 ${prefix}.production.lammpstrj id mol type xu yu zu vx vy vz
dump_modify production sort id format float %20.10g
fix npt_production all npt temp 300.0 300.0 100.0 iso 1.0 1.0 100.0
run 10000
unfix npt_production
undump production

#===========================================================
# Clean and exit
#===========================================================

write_data ${prefix}.end.data
unfix averages
unfix mom
